"""
APScheduler integration — fires the workbook pipeline on a cron schedule.
The cron expression is read from WORKBOOK_SCHEDULE_CRON (default: Mondays 9am UTC).
"""

import logging
import uuid

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

from app.config import settings
from app.database import SessionLocal
from app.models import JobStatus, WorkbookJob

logger = logging.getLogger(__name__)
_scheduler = BackgroundScheduler()


def _scheduled_workbook_run() -> None:
    from app.tasks import run_workbook_pipeline

    db = SessionLocal()
    try:
        job = WorkbookJob(
            id=str(uuid.uuid4()),
            module_title="Scheduled Module",
            learning_objectives="Auto-generated by scheduled run. Edit learning objectives in the trigger API for custom runs.",
            status=JobStatus.pending,
        )
        db.add(job)
        db.commit()
        run_workbook_pipeline.delay(job.id)
        logger.info("Scheduled workbook job %s enqueued", job.id)
    finally:
        db.close()


def start_scheduler() -> None:
    parts = settings.workbook_schedule_cron.split()
    if len(parts) != 5:
        logger.warning("Invalid WORKBOOK_SCHEDULE_CRON, skipping scheduler setup")
        return

    minute, hour, day, month, day_of_week = parts
    trigger = CronTrigger(
        minute=minute,
        hour=hour,
        day=day,
        month=month,
        day_of_week=day_of_week,
        timezone="UTC",
    )
    _scheduler.add_job(_scheduled_workbook_run, trigger=trigger, id="workbook_cron")
    _scheduler.start()
    logger.info("Scheduler started with cron: %s", settings.workbook_schedule_cron)


def stop_scheduler() -> None:
    if _scheduler.running:
        _scheduler.shutdown()
