"""
Fill Canva from a pre-generated workbook JSON, then email the edit link.

This is the deterministic half of the subscription-based flow: content is
generated by Claude Code (via the generate-workbook skill, using your Pro/Max
plan and brand-voice sources), written to a JSON file, then handed here.

It does NOT generate content and has NO Anthropic dependency — it validates the
JSON against the WorkbookContent schema, autofills the Canva template, and
notifies the reviewer. Runtime-agnostic: works whether called by the skill,
by cron, or by hand.

  python scripts/fill_canva.py --content out/workbook-2026-07.json --mese "Luglio 2026"

The JSON must match the WorkbookContent schema (34 fields). See
app/pipelines/workbook/generate.py or the generate-workbook skill for the shape.
"""

import argparse
import json
import sys
from datetime import date
from pathlib import Path

import httpx
from pydantic import ValidationError

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.config import settings  # noqa: E402
from app.integrations import canva_client  # noqa: E402
from app.pipelines.workbook import backgrounds, content_plan, notify  # noqa: E402
from app.pipelines.workbook.generate import (  # noqa: E402
    WorkbookContent,
    workbook_to_canva_fields,
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Fill Canva from a workbook JSON + notify")
    parser.add_argument("--content", required=True, help="Path to the workbook JSON file")
    parser.add_argument("--mese", help='Edition label, e.g. "Luglio 2026" (default: today)')
    parser.add_argument("--tema", default="", help="Theme line for the email (optional)")
    parser.add_argument(
        "--no-email", action="store_true", help="Skip the notification (just print the URL)"
    )
    args = parser.parse_args()

    if not settings.canva_template_id:
        sys.exit("CANVA_TEMPLATE_ID is not set in .env.")

    mese = args.mese or content_plan.edition_label(date.today())

    content_path = Path(args.content)
    if not content_path.exists():
        sys.exit(f"Content file not found: {content_path}")

    # Validate the generated JSON against the schema — a bad shape fails loudly
    # here rather than silently producing a half-filled design.
    try:
        data = json.loads(content_path.read_text())
        content = WorkbookContent(**data)
    except json.JSONDecodeError as exc:
        sys.exit(f"✗ {content_path} is not valid JSON: {exc}")
    except ValidationError as exc:
        sys.exit(f"✗ Content does not match the 34-field WorkbookContent schema:\n{exc}")

    fields = workbook_to_canva_fields(content)
    print(f"Validated content → {len(fields)} autofill fields. Cover: «{content.cover_title}»")

    image_fields = backgrounds.pick_background_fields(mese)

    print(f"Autofilling Canva template {settings.canva_template_id} for «{mese}» …")
    try:
        design_id = canva_client.create_design_from_template(
            fields, image_fields=image_fields, title=f"WB HDH {mese}"
        )
    except httpx.HTTPStatusError as exc:
        sys.exit(f"✗ Canva autofill failed: {exc.response.status_code} — {exc.response.text}")
    except Exception as exc:
        sys.exit(f"✗ Canva autofill failed: {type(exc).__name__}: {exc}")

    edit_url = f"https://www.canva.com/design/{design_id}/edit"
    print(f"✓ Design ready: {edit_url}")

    if not args.no_email:
        tema = args.tema or content.cover_title
        notify.send_ready(edition_label=mese, edit_url=edit_url, tema=tema)
        print("✓ Notification sent (or skipped if email not configured).")


if __name__ == "__main__":
    main()
